# Generated by Django 4.1.1 on 2022-09-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0002_delegate_last_mail_alter_option_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="delegate",
            name="mail_failed",
            field=models.BooleanField(default=False),
        ),
    ]
