# Generated by Django 4.1.1 on 2022-09-27 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vote", "0003_delegate_mail_failed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="delegate",
            name="last_mail",
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0)),
        ),
    ]
