# Generated by Django 4.1.6 on 2025-08-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_delegate_last_mail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delegate',
            options={'ordering': ('delegated_by', 'user')},
        ),
        migrations.AddField(
            model_name='question',
            name='secret',
            field=models.BooleanField(default=False),
        ),
    ]
